name: Analysis

on:
  push:
    branches:
      - master

jobs:
  metric_tracking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip3 install git+https://github.com/paulgessinger/headwind.git@eeeaa80
      - name: Run publish
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          wget https://raw.githubusercontent.com/paulgessinger/acts/perf-tracking/CI/headwind.yml
          rm -rf report
          hdw publish headwind.yml report
          git add report
          git commit -m"update report"
          git push

