name: Analysis

on:
  push:
    branches:
      - master

jobs:
  make_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip3 install git+https://github.com/paulgessinger/headwind.git@eeeaa80
      - name: Run publish
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          rm -rf report
          hdw publish headwind.yml report
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: report # The folder the action should deploy.

